/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracosRouteImport } from './routes/tracos'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TracosRoute = TracosRouteImport.update({
  id: '/tracos',
  path: '/tracos',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparador': typeof ComparadorRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/dashboard': typeof DashboardRoute
  '/insumos': typeof InsumosRoute
  '/mais': typeof MaisRoute
  '/produtos': typeof ProdutosRoute
  '/testes': typeof TestesRoute
  '/tracos': typeof TracosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparador': typeof ComparadorRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/dashboard': typeof DashboardRoute
  '/insumos': typeof InsumosRoute
  '/mais': typeof MaisRoute
  '/produtos': typeof ProdutosRoute
  '/testes': typeof TestesRoute
  '/tracos': typeof TracosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparador': typeof ComparadorRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/custos': typeof CustosRoute
  '/dashboard': typeof DashboardRoute
  '/insumos': typeof InsumosRoute
  '/mais': typeof MaisRoute
  '/produtos': typeof ProdutosRoute
  '/testes': typeof TestesRoute
  '/tracos': typeof TracosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comparador'
    | '/configuracoes'
    | '/custos'
    | '/dashboard'
    | '/insumos'
    | '/mais'
    | '/produtos'
    | '/testes'
    | '/tracos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comparador'
    | '/configuracoes'
    | '/custos'
    | '/dashboard'
    | '/insumos'
    | '/mais'
    | '/produtos'
    | '/testes'
    | '/tracos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comparador'
    | '/configuracoes'
    | '/custos'
    | '/dashboard'
    | '/insumos'
    | '/mais'
    | '/produtos'
    | '/testes'
    | '/tracos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComparadorRoute: typeof ComparadorRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CustosRoute: typeof CustosRoute
  DashboardRoute: typeof DashboardRoute
  InsumosRoute: typeof InsumosRoute
  MaisRoute: typeof MaisRoute
  ProdutosRoute: typeof ProdutosRoute
  TestesRoute: typeof TestesRoute
  TracosRoute: typeof TracosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracos': {
      id: '/tracos'
      path: '/tracos'
      fullPath: '/tracos'
      preLoaderRoute: typeof TracosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComparadorRoute: ComparadorRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CustosRoute: CustosRoute,
  DashboardRoute: DashboardRoute,
  InsumosRoute: InsumosRoute,
  MaisRoute: MaisRoute,
  ProdutosRoute: ProdutosRoute,
  TestesRoute: TestesRoute,
  TracosRoute: TracosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
